### ISSUE TITLE
Are we capturing NIST's reccomendation on SMS authentication accurately? 

### ISSUE THREAD

**Issue by amandabee** [OpenNewsLabs/field-guide-security-training-newsroom#10]
[Chapter 02-07](https://github.com/OpenNewsLabs/newsroom-security-curricula/blob/master/drafts/Chapter02-07-Two-Factor-Authentication.md)  we refer to tentative NIST recommendations from 2016 -- need to review http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63b.pdf via https://pages.nist.gov/800-63-3/ to confirm that we're accurately representing NIST's recs on SMS authentication.

**Comment by b-meson** [comment]
Essentially NIST is recommending to deprecate SMS 2FA in favor of TOTP or HOTP (either using google Authenticator or applications like that OR using a hardware token like a yubikey). That being said, using SMS 2FA is still better than not using 2FA (i.e the state of T-Mobile security as of this comment date)
