### ISSUE TITLE
Add chapter links to ToC section in index.md

### ISSUE THREAD

**Issue by ryanpitts** [OpenNewsLabs/field-guide-security-training-newsroom#15]
At some point we need to [replace "TK: Links to chapters" here](https://github.com/OpenNewsLabs/newsroom-security-curricula/blob/master/docs/index.md#table-of-contents) with actual links. Could probably start doing that now and just keep it updated as new lessons land.

**Comment by zenmonkeykstop** [comment]
Added basic TOC  - would be cool if this was generated instead tbh but not clear to me how to do that in rtd-flavoured markdown. Will investigate.

**Comment by ryanpitts** [comment]
Yeah, I'd be interested to hear if you come across any automated solutions like that. I think Sphinx can do things like auto generation, but swapping from Markdown to Sphinx seems like it might community contributions more intimidating.

**Comment by ryanpitts** [comment]
Let's close this one—at this point, I don't think there's an automated fix here.
