### ISSUE TITLE
Review lesson formatting as presented on Read The Docs

### ISSUE THREAD

**Issue by ryanpitts** [OpenNewsLabs/field-guide-security-training-newsroom#17]
I'm noticing a couple things we might want to tweak in the standard lesson formatting based on the way they're rendered on RTD. [See "Mobile App Security Settings" as an example](https://the-field-guide-to-security-training-in-the-newsroom.readthedocs.io/en/latest/Chapter02-01-Mobile-Security-Settings/).

Opening this thread as a place to log things so we can A) fix them on existing lessons, and B) adjust how we're formatting lessons still in progress. Please [take a look](https://the-field-guide-to-security-training-in-the-newsroom.readthedocs.io/en/latest/Chapter02-01-Mobile-Security-Settings/) and note any questions or observations here!

**Comment by ryanpitts** [comment]
The first thing jumping out at me is the missing linebreaks in spots like this.

![screen shot 2018-01-10 at 1 31 32 pm](https://user-images.githubusercontent.com/56477/34796646-fab8b368-f60a-11e7-9935-f4e4bae9ee1e.png)

RTD and GitHub use the same Markdown renderer, where you can make sure there are linebreaks throughout single-spaced sections of text by adding 2 spaces at the end of each of those lines. (Don't ask me why that's the fix, but I've run into this before!)

**Comment by zenmonkeykstop** [comment]
I ran into this updating resources page as it happens (PR TK) - Stuck in <br/>s, but will replace with double spaces

**Comment by zenmonkeykstop** [comment]
Corrected line break issues as mentioned above.

**Comment by ryanpitts** [comment]
Noting that the draft version on Read The Docs now lives at https://the-field-guide-to-security-training-in-the-newsroom.readthedocs.io/en/latest/
