### ISSUE TITLE
change repo name

### ISSUE THREAD

**Issue by ryanpitts** [OpenNewsLabs/field-guide-security-training-newsroom#21]
Given the project title on RTD, we should change the repo name to `field-guide-security-training-newsroom`. I'll need to update the RTD settings and this will also break the remote URL for any local clones of this repo, so will wait for your 👍 @zenmonkeykstop and @amandabee

**Comment by zenmonkeykstop** [comment]
Do it, can fix up remotes after.

**Comment by amandabee** [comment]
:+1:

**Comment by ryanpitts** [comment]
OK great, everything's updated.
