### ISSUE TITLE
Update Chapter02-00-Overview in /drafts

### ISSUE THREAD

**Issue by ryanpitts** [OpenNewsLabs/field-guide-security-training-newsroom#22]
- update lesson links to point them toward published versions that will work on RTD
- make lesson titles consistent
- make tone of summaries consistent
- write super short intro giving this context: "here are capsule summaries of the lessons in this chapter"

**Comment by amandabee** [comment]
Add: here's what you won't see and why. GPG is hard to do right, but there are good journalism use cases. We welcome a good lesson plan but haven't made one.

**Comment by amandabee** [comment]
This needs a read and maybe some context wrapping, but I did migrate the links and lesson titles. 
Are the URLs accurate @ryanpitts ?

**Comment by ryanpitts** [comment]
will do a read on this

**Comment by ryanpitts** [comment]
I'll fix these as I go through, but to answer your question about URLs: none of the links within the guide need the "docs/" prefix. Everything will be local within the `docs` directory, so just linking by filename should be all you need.

**Comment by ryanpitts** [comment]
OK, made some edits here: https://github.com/OpenNewsLabs/field-guide-security-training-newsroom/blob/master/drafts/Chapter02-00-Overview.md. Among other small fixes, I revised so that all uses of "you" were referring to the trainer, who I think is the only audience for this document.

I also have a super nagging feeling about Ch2-02-MobileBackups. It appears right in the middle of three lessons that are described as a three-part series. And tbh it is kind of making my teeth hurt that the series is made up of files 01, 03, and 04. Can we flip MobileBackups to the 4th position here and revise links before we get too deep into publication?

**Comment by amandabee** [comment]
Yes, we can.

On February 28, 2018 5:10:50 PM PST, Ryan Pitts <notifications@github.com> wrote:
>OK, made some edits here:
>https://github.com/OpenNewsLabs/field-guide-security-training-newsroom/blob/master/drafts/Chapter02-00-Overview.md.
>Among other small fixes, I revised so that all uses of "you" were
>referring to the trainer, who I think is the only audience for this
>document.
>
>I also have a super nagging feeling about Ch2-02-MobileBackups. It
>appears right in the middle of three lessons that are described as a
>three-part series. And tbh it is kind of making my teeth hurt that the
>series is made up of files 01, 03, and 04. Can we flip MobileBackups to
>the 4th position here and revise links before we get too deep into
>publication?
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenNewsLabs/field-guide-security-training-newsroom/issues/22#issuecomment-369440211

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by amandabee** [comment]
We might need to do a batch search to fix that. I may have used "docs/" throughout.

On February 28, 2018 4:37:21 PM PST, Ryan Pitts <notifications@github.com> wrote:
>I'll fix these as I go through, but to answer your question about URLs:
>none of the links within the guide need the "docs/" prefix. Everything
>will be local within the `docs` directory, so just linking by filename
>should be all you need.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenNewsLabs/field-guide-security-training-newsroom/issues/22#issuecomment-369433626

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ryanpitts** [comment]
I'll take care of both of these things

**Comment by ryanpitts** [comment]
OK, files moved around and links updated in https://github.com/OpenNewsLabs/field-guide-security-training-newsroom/commit/7d2a58e04f5d4f8658fba88d8536b7a8c84a95d9

**Comment by ryanpitts** [comment]
Whoops, didn't mean to close this one quite yet. This document still has outline notes at the top, and I'm not sure whether there's any more material to add. @amandabee?
