### ISSUE TITLE
style edit on Chapter01-04-PathwaysChoosingLessons in drafts

### ISSUE THREAD

**Issue by ryanpitts** [OpenNewsLabs/field-guide-security-training-newsroom#24]
Make things more tonally consistent. Some spots currently use plural possessive, or state that we are making assumptions—our style is to keep things simple, straightforward and direct. Should follow the tone in lessons in /docs.

**Comment by amandabee** [comment]
I wound up pulling a lot out -- much of the material is also covered in being a better trainer, or in frameworks.
