### ISSUE TITLE
Edit and Revise "Pathways"

### ISSUE THREAD

**Issue by amandabee** [OpenNewsLabs/field-guide-security-training-newsroom#3]
We’ve started work on an additional piece of Chapter 1: a [guide to possible pathways in the curriculum](https://github.com/OpenNewsLabs/newsroom-security-curricula/blob/master/drafts/Chapter01-04-PathwaysChoosingLessons.md), to help people get the most out of the curriculum. 
    
We’d love to add this guide to the published curriculum. Right now it’s a rough draft that needs cleanup, tightening, writing, and editing. It would be fantastic if you could pick up this document and carry it over the finish line.

**Comment by ryanpitts** [comment]
Closing, this is captured in https://github.com/OpenNewsLabs/field-guide-security-training-newsroom/issues/37
