### ISSUE TITLE
add new lesson from Minneapolis Star-Tribune?

### ISSUE THREAD

**Issue by ryanpitts** [OpenNewsLabs/field-guide-security-training-newsroom#35]
Alan Palazzolo posted this outline of a newsroom security lesson in the News Nerdery Slack. Seems like something we could ask him if he'd be willing to PR into the curriculum here.

https://docs.google.com/document/d/1JRih1PT0PVOrNxp0hGu6jooOfjwqGzUb4SjK71zvpPU/edit

What do you think @amandabee @zenmonkeykstop?

**Comment by amandabee** [comment]
Yes. 

His post actually sent me down a rabbit hole because we don't have a good way to accommodate documents like this that are real adaptations for a specific purpose.

I did actually point him to the two drafts that are most relevant to his session, too.

**Comment by ryanpitts** [comment]
Let's flag this for our Friday checkin this week—we should talk about how to invite PRs like this, whether we should ask for formatting, whether we offer to reformat, etc.

**Comment by zenmonkeykstop** [comment]
This looks to me like it could be repurposed for the pathways doc, & also be a standalone lesson plan for situations where you have to cover a bunch of basic topics quickly. That might be the way to look at it: "only have 1 hour for everything? use this plan!"

**Comment by ryanpitts** [comment]
I like that approach a lot. Offering the "Covering the basics over a lunch hour" lesson plan would be sweet.

**Comment by ryanpitts** [comment]
flagging that we should check in with Alan to see if he has run this as a workshop yet, and if so about how long it took to cover the material.

**Comment by ryanpitts** [comment]
also would need an editing pass here to remove specific references to Star-Tribune policies

**Comment by ryanpitts** [comment]
Alan chatting with Alan about getting this into our format for publication here.

**Comment by ryanpitts** [comment]
Noting that we are thinking Chapter2-Overview-LESSONNAME.md

**Comment by amandabee** [comment]
We're going to file this in Chapter 2 - Overview  -- and categorize overview lessons separate from the deep dive lessons.

**Comment by amandabee** [comment]
This is up. I asked Alan about how he wants to be credited. Will add that when he replies.
