### ISSUE TITLE
NICAR plan?

### ISSUE THREAD

**Issue by amandabee** [OpenNewsLabs/field-guide-security-training-newsroom#38]
Should we actually do something at NICAR? I don't mean 🍾🥂 but convening folks who are interested in doing more trainings in their newsroom to talk about how the guide exists and we want people to use it and give us feedback? (adding an issue so we can discuss on our next call)

**Comment by ryanpitts** [comment]
Per call 2/23, we'll start by reaching out about a spot in the conversations track

**Comment by amandabee** [comment]
We're going to bring the resource to the conversations that are planned; Martin is no longer leading the "overview of security tools" workshop -- Amanda will talk to JM who is now leading it.

**Comment by amandabee** [comment]
It would be great to plug our best practices document (plus invite feedback) in Martin's talk on secure tips pages.
