### ISSUE TITLE
Why isn't there a lesson on GPG?

### ISSUE THREAD

**Issue by amandabee** [OpenNewsLabs/field-guide-security-training-newsroom#39]
Somewhere we need to explain why we omitted GPG / email encryption from the curriculum.

The reasons are these:

Most trainings just shouldn't cover pgp for email:
https://source.opennews.org/articles/how-lose-friends-and-anger-journalists-pgp/

And for folks who are committed to using it, there are great walk-throughs already:
https://emailselfdefense.fsf.org/en/

Setting up a throw away protonmail account is a better strategy for short term communication. 

The question is: where do we say that?

**Comment by ryanpitts** [comment]
Per call 2/23, we aren't going to make a lesson on this right now. Very hard to use, not even really recommended to use by most security folks, but we would love to figure out a place to explain this as context. "You're probably looking for a lesson on GPG, here's why there isn't one here."

Solution we discussed was adding a "here's what you won't find here" section to Ch2-00-Overview https://github.com/OpenNewsLabs/field-guide-security-training-newsroom/issues/22
