### ISSUE TITLE
apply edits suggested by Martin/Emma's readthrough

### ISSUE THREAD

**Issue by ryanpitts** [OpenNewsLabs/field-guide-security-training-newsroom#44]
Notes here: https://docs.google.com/document/d/1LWeo3rtveRA-WcDxPC3zECxR9ZfK0Q4UG7muD_EviOc/edit

**Comment by zenmonkeykstop** [comment]
Chapter 2 edits done. Chapter 1, 3 next.

**Comment by zenmonkeykstop** [comment]
Edits done.
