### ISSUE TITLE
Editors not listed?

### ISSUE THREAD

**Issue by amandabee** [OpenNewsLabs/field-guide-security-training-newsroom#50]
Currently index.rst only lists Chicago convening participants, but not folks who provided edits afterwards or submitted new lessons (alan palazzolo) -- we should add those folks.

**Comment by amandabee** [comment]
(I added two. But @ryanpitts do you know who else is missing?)

**Comment by ryanpitts** [comment]
yep, added the rest of the folks who agreed to help out as editors. https://github.com/OpenNewsLabs/field-guide-security-training-newsroom/commit/2dcb5e05943a636eb1be5fba11c462cbe446e93a
