### ISSUE TITLE
Readme needs contact info and a read

### ISSUE THREAD

**Issue by amandabee** [OpenNewsLabs/field-guide-security-training-newsroom#51]
Do we want to hear about people who use this (probably...)? Then we should invite that specifically, either by asking for "issues" with stories about using the guide, or by giving folks an email address. I'm happy to field emails, but the address should probably be opennews.

**Comment by ryanpitts** [comment]
closed in https://github.com/OpenNewsLabs/field-guide-security-training-newsroom/commit/a82b374ba80cbbf651d00e04184f759e9330e192
