### ISSUE TITLE
review lessons for updates from NICAR

### ISSUE THREAD

**Issue by ryanpitts** [OpenNewsLabs/field-guide-security-training-newsroom#53]
NICAR resources to review in this list: http://blog.chryswu.com/2018/01/23/nicar18-slides-links-tutorials/

**Comment by amandabee** [comment]
Intro: 
https://docs.google.com/document/d/1q3gBvOEviV_0XMpMjvBiHSaKcl64uu4NwOoEVfXyYqU/edit# 

and 
Tips Page: 
https://docs.google.com/presentation/d/1P9-C6TK2GfWZ0CPGkN7YmOeDqNtoktNd6ETueD7EohI/edit#slide=id.p 

Are the two worth adding. The Tips page is easy. The other is more of an overview, consistent with Alan's lesson. 

are the two links that actually made it onto the resource list.

**Comment by amandabee** [comment]
Found homes for both of these.
