### ISSUE TITLE
Reorder/Rename Ch 3 docs

### ISSUE THREAD

**Issue by amandabee** [OpenNewsLabs/field-guide-security-training-newsroom#63]
Currently,  Ch3 reads like this: 

> Chapter 3 - Resources
> 
>     Concept Glossary
>     Chapter 3: Resources for building further expertise
>     Best Practices for a Tips Page

I think that Resources should be either first or last, and if anything is going to have "Chapter 3" in its name, it should be the first piece in the chapter.

**Comment by zenmonkeykstop** [comment]
Agreed. Will fix

**Comment by ryanpitts** [comment]
done
