### ISSUE TITLE
Serve field guide over HTTPS

### ISSUE THREAD

**Issue by knowtheory** [OpenNewsLabs/field-guide-security-training-newsroom#64]
Hey folks,

Given that this is a security guide, i would like to [strongly recommend serving the guide over HTTPS only](https://the-field-guide-to-security-training-in-the-newsroom.readthedocs.io/en/latest/Chapter03-03-OrgBestPractices.html?highlight=HTTPS#before-we-talk-about-tools).

Unfortunately [ReadTheDocs customized domains cannot be directly configured to for HTTPS](https://docs.readthedocs.io/en/latest/alternate_domains.html?highlight=SSL#cname-ssl), and they recommend using a proxy w/ HTTPS as front end.

One option for doing so is using [a service such as Cloudflare](https://www.cloudflare.com/plans/) (which is free in Cloudflare's case).  The ReadTheDocs link above also suggests using a server which just does a proxy pass and fronts the HTTPS itself.

Happy to lend a hand or discuss the topic!

**Comment by ryanpitts** [comment]
Yep, we've been discussing this internally as well. Thanks Ted!

**Comment by ryanpitts** [comment]
@knowtheory FWIW, I think Cloudflare is only an option if I move the entire opennews.org domain to Cloudflare's nameservers. Unless I'm missing something, can't just set it up for securitytraining.opennews.org. Testing it out today, but doesn't look like it should work for subdomain only.

**Comment by ryanpitts** [comment]
wonder if it's possible through cloudfront shenanigans

**Comment by knowtheory** [comment]
Oh yeah, that definitely should be possible.  If you were running this on straight AWS i'd say "just set up an Elastic Load Balancer and turn on AWS's free certificate management (IT IS GREAT) and then you're literally done.

But in this case i'm not 100% sure how to plug your thing into the ELB.  You i guess could spin up a tiny instance w/ NGINX that just receives requests behind the ELB and then proxy passes it RTD.

**Comment by knowtheory** [comment]
But cloudfront as a distribution should also be able to point to it.  Lemme go search some docs.

**Comment by knowtheory** [comment]
Oh yeah.  I forgot, [you can set CloudFront up to point to a custom origin](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html).

**Comment by ryanpitts** [comment]
Yep was just looking at those docs too—we use CloudFront for a ton of other stuff, so would really prefer to find a solution here.

**Comment by knowtheory** [comment]
Yeah, so in that case i think it's just a matter of setting up a CloudFront distribution with RTD as a Custom Origin and then pointing the DNS record to the distribution

**Comment by knowtheory** [comment]
Shouldn't be too bad in this case esp since everything is read only and caching times don't matter especially.

**Comment by ryanpitts** [comment]
hmmmm, currently working but only kind of. Cloudfront forwarding securitytraining.opennews.org to https://the-field-guide-to-security-training-in-the-newsroom.readthedocs.io/en/latest/, not serving it under our domain.

**Comment by ryanpitts** [comment]
Just noting that https://securitytraining.opennews.org is currently working _as a redirect_ to the https RTD site for this project. Have a ticket open with RTD to see if it's possible to make Cloudfront work like we want it to, but possible that we would just need to spin up an EC2 proxy server to make this work like we want.

**Comment by ryanpitts** [comment]
https://github.com/rtfd/readthedocs.org/issues/3938

**Comment by ryanpitts** [comment]
closing this one because HTTPS is enforced, will open a new ticket to specifically reflect the work on serving this via custom domain
